// Persistent AI learning plane — create. Secrets: generated by scripts/stack-up.ps1 into the operator environment; never committed.
using '../main-ai.bicep'

param location = 'centralus'
param uniqueSuffix = readEnvironmentVariable('GBA_UNIQUE_SUFFIX')
param addressPrefix = '10.30.0.0/16'
param acaSubnetPrefix = '10.30.0.0/23'
param peSubnetPrefix = '10.30.2.0/27'
param appInsightsId = readEnvironmentVariable('GBA_APPINSIGHTS_ID')
param containerRegistryId = readEnvironmentVariable('GBA_ACR_ID')
param acrLoginServer = readEnvironmentVariable('GBA_ACR_LOGIN_SERVER')
param logAnalyticsWorkspaceId = readEnvironmentVariable('GBA_LOG_WORKSPACE_ID')
param aiWorkerImage = readEnvironmentVariable('GBA_AI_IMAGE', '')
param operatorPrincipalId = readEnvironmentVariable('GBA_OPERATOR_OBJECT_ID')
param deployGpuCluster = false
// Azure ML quota read 2026-10-01 (centralus): standardDDSv5Family 4 vCPUs; D4ds_v5 has 4.
param cpuMaxNodes = 1
// The dedicated AI jobs environment (ADR-0013) moved to stack gorgona-ai-jobs
// (main-ai-jobs.bicep, jobs_region westus3): Central US refused new Container Apps
// environments twice on 2026-10-01 (ManagedEnvironmentCapacityHeavyUsageError). Never
// true here again without an owner decision: it would retry the Central US environment.
// On the next gorgona-ai update the failed cae-gorgona-ai is DETACHED (detachAll), not
// deleted; deleting it is a separate owner approval.
param deployJobsEnvironment = false
param lockResourceGroup = true
param postgresAdminPassword = readEnvironmentVariable('GBA_AI_PG_ADMIN_PASSWORD')
param ownerRolePassword = readEnvironmentVariable('GBA_AI_OWNER_ROLE_PASSWORD')
param workerRolePassword = readEnvironmentVariable('GBA_AI_WORKER_ROLE_PASSWORD')
